### ISSUE TITLE
How do you run gpt-neo in clover edition?

### ISSUE THREAD

**Issue by Skhmt** [finetuneanon/gpt-neo_dungeon#1]
Is that even possible? If so, what are the steps to do it?

**Comment by mrseeker** [comment]
Wrong repository... Ask here-> https://github.com/cloveranon/Clover-Edition

**Comment by Skhmt** [comment]
I asked here because it says "If you integrate the models in clover edition..." in the instructions in this repo and mentions some limited things to do (replace transformer with a fork), but where do I go from there?

**Comment by finetunej** [comment]
Did that earlier today. Check here:
https://github.com/finetuneanon/Clover-Edition
