### ISSUE TITLE
Get better prompt and UI of commands in Colab?

### ISSUE THREAD

**Issue by slasken10** [finetuneanon/gpt-neo_dungeon#2]
Hi!
Im not a developer and are bad at colab so im sorry if even raising this issue is wrong.

Is it possible to get a better and easier controllable output then the current one?
I find it very frustrating to edit, reverse etc and the whole story easily goes out of control(because of the weird focus)
Can i somehow import a more decent prompt or connect to the colab engine trough pshell or bash?

Thank you sir for your work.

**Comment by mrseeker** [comment]
Could be the "nature of the beast" I would say. KoboldAI runs locally and can run the same model. You can try running /bin/bash and use homemade scripts, or create a better version (and do a pull request?)

**Comment by slasken10** [comment]
> 
> 
> Could be the "nature of the beast" I would say. KoboldAI runs locally and can run the same model. You can try running /bin/bash and use homemade scripts, or create a better version (and do a pull request?)

Sure i could, i am not yet familiar with all the features of google colab. But if it is possible to get a normal bash prompt and it works as a normal Linux distro i would be probably be able to play around.
KolabAI requires 8GB of VRAM and as i have a old GTX 1080 with 8gb it works in theory but then i have to close down everything and drop to a shell to be able to start it(as my Xorg pulls around 300mb in VRAM).

**Comment by finetunej** [comment]
Colab is limited as far as user interfaces go. It probably won't get much better.

You can just copy and paste a long prompt in the input box and press generate. Each line will turn into an action, so it won't cause issues if you paste in a full story. I recommend writing the story in 1st or 3rd person and basically the way you would use with /story for best results.

**Comment by slasken10** [comment]
Thanks!
I will play around a little bit.
Very hard to keep the AI back on track tough.
It works with remember to bring the AI back on track but after a while it will just repeat its output no matter what.

Anyway, not an Issue, ill guess ill leave this to the people more expierenced in deeplearning and colab.

**Comment by mrseeker** [comment]
> Very hard to keep the AI back on track tough.
> It works with remember to bring the AI back on track but after a while it will just repeat its output no matter what.
> 
> Anyway, not an Issue, ill guess ill leave this to the people more expierenced in deeplearning and colab.

Note that the AI is more focussed on storytelling and uses the input from previous responses to craft a new response. If you find yourself stuck in a "loop", try upping the repetition_penalty to 1.75, that seems to be a sweetspot between novel output and repeating itself. Higher and it tends to go all over the place, lower and it keeps repeating itself. Another option would be the temperature, which controls the amount of "artistic freedom" that you give the AI. AID uses 1.0, but I recommend 0.7-0.9 for best effects.
