### ISSUE TITLE
fp32 for big GPUs discards information

### ISSUE THREAD

**Issue by Frogging101** [finetuneanon/gpt-neo_dungeon#3]
In model setup where we check the GPU memory and then bring the model back up to fp32:
```py
if torch.cuda.get_device_properties(0).total_memory > 15000 * 1024 * 1024:
  print("Big GPU detected, using fp32")
  model = model.float()
```

Isn't this doing nothing useful, because we have already `half()`'d the model into fp16? Can't just bring that precision back.

**Comment by finetunej** [comment]
It's useful in sofar as intermediate activations will be calculated in fp16. I've recently removed the upcasting however, because I added a workaround to the torch.multinomial fp16 bug in my transformers fork.
